### ISSUE TITLE
Doesn't compile with gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

### ISSUE THREAD

**Issue by mlliarm** [johnliu55tw/ALSASoundMeter#1]
But it compiles just nice with clang version 3.8.0-2ubuntu4, and the executable works smoothly.

The errors that I get if I run make (with gcc) are:

/tmp/ccqMjrgS.o: In function `rms':
sound_meter.c:(.text+0x7b): undefined reference to `sqrt'
/tmp/ccqMjrgS.o: In function `main':
sound_meter.c:(.text+0x122): undefined reference to `snd_pcm_open'
sound_meter.c:(.text+0x135): undefined reference to `snd_strerror'
sound_meter.c:(.text+0x181): undefined reference to `snd_pcm_set_params'
sound_meter.c:(.text+0x198): undefined reference to `snd_strerror'
sound_meter.c:(.text+0x1f2): undefined reference to `snd_pcm_readi'
sound_meter.c:(.text+0x216): undefined reference to `snd_pcm_recover'
sound_meter.c:(.text+0x22d): undefined reference to `snd_strerror'
sound_meter.c:(.text+0x298): undefined reference to `log10'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'sound_meter' failed
make: *** [sound_meter] Error 1

**Comment by johnliu55tw** [comment]
This issue is fixed by @bendahl with #2 .
